version: "3.8"

services:
  listing-service:
    build:
      context: ../ListingService/ListingServiceAPI
    ports:
      - "5136:5136"
    environment:
      MongoConnectionString: mongodb://mongo:27017
      CatalogDatabase: ListingDB
      CatalogCollection: Listings
    depends_on:
      - mongo

  catalog-service:
    build:
      context: ../CatalogService/CatalogServiceAPI
    ports:
      - "5266:5266"
    environment:
      MongoConnectionString: mongodb://mongo:27017
      CatalogDatabase: CatalogDB
      CatalogCollection: Catalogs
      ListingServiceBaseUrl: http://listing-service:5136
    depends_on:
      - listing-service
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
