version: "3.8"

services:
  listing-service:
    build:
      context: ../ListingService/ListingServiceAPI
    ports:
      - "5136:5136"
    environment:
      MongoConnectionString: mongodb://mongo:27017
      CatalogDatabase: ListingDB
      CatalogCollection: Listings
    depends_on:
      - mongo
    networks:
      - observability

  catalog-service:
    build:
      context: ../CatalogService/CatalogServiceAPI
    ports:
      - "5266:5266"
    environment:
      MongoConnectionString: mongodb://mongo:27017
      CatalogDatabase: CatalogDB
      CatalogCollection: Catalogs
      ListingServiceBaseUrl: http://listing-service:5136
    depends_on:
      - listing-service
      - mongo
    networks:
      - observability

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - observability
        
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/var/log/loki
    networks:
      - observability
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "gruppe1"     
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - observability


volumes:
  mongo-data:
  grafana-data:
  loki-data:
  wal:
    
networks:
  observability:

